### ISSUE TITLE
rpi3b with not working bluetooth error/debug logs

### ISSUE THREAD

**Issue by dogi** [treehouses/cli#238]
after `treehouses bluetooth on` the file `/etc/bluetooth-id` was not created ...
also
```
systemctl status rpibluetooth
● rpibluetooth.service - Bluetooth server
   Loaded: loaded (/etc/systemd/system/rpibluetooth.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-01-23 23:17:30 GMT; 31min ago
  Process: 473 ExecStart=/usr/bin/python3 /usr/local/bin/bluetooth-server.py & (code=exited, status=1/FAILURE)
 Main PID: 473 (code=exited, status=1/FAILURE)
      CPU: 471ms

Jan 23 23:17:30 treehouses python3[473]: Exception ignored in: <bound method BluetoothServer.__del__ of <__main__.BluetoothServer object at 0x76538df0>>
Jan 23 23:17:30 treehouses python3[473]: Traceback (most recent call last):
Jan 23 23:17:30 treehouses python3[473]:   File "/usr/local/bin/bluetooth-server.py", line 45, in __del__
Jan 23 23:17:30 treehouses python3[473]:     self.Close()
Jan 23 23:17:30 treehouses python3[473]:   File "/usr/local/bin/bluetooth-server.py", line 50, in Close
Jan 23 23:17:30 treehouses python3[473]:     if self._closed:
Jan 23 23:17:30 treehouses python3[473]: AttributeError: 'BluetoothServer' object has no attribute '_closed'
Jan 23 23:17:30 treehouses systemd[1]: rpibluetooth.service: Main process exited, code=exited, status=1/FAILURE
Jan 23 23:17:30 treehouses systemd[1]: rpibluetooth.service: Unit entered failed state.
Jan 23 23:17:30 treehouses systemd[1]: rpibluetooth.service: Failed with result 'exit-code'.
```

**Comment by dogi** [comment]
`treehouses detectbluetooth`?

**Comment by dogi** [comment]
hmm found by comparison a raspberrypi with defect bluetooth ...
